### DISCUSSION TITLE
Possible to pass a color and a box shadow to the scrollbar track?

### DISCUSSION THREAD

**Discussion by BenjaminHoefer** [KingSora/OverlayScrollbars#569] [Q&A] [answered]
Hi! I am just wondering if it is possible to give the scrollbar track a specific color and a box shadow since there has not been a parameter to pass a shadow. I am trying it right now but I could not fix my issue yet.

**Comment by KingSora** [comment, marked as answer]
@BenjaminHoefer Good day :)

Besides the `css custom properties`, you can pass add almost _any_ style to the scrollbar, scrollbar-track or scrollbar-handle.
For example you could do this:

```css
.os-scrollbar > .os-scrollbar-track {
  box-shadow: 0 0 5px 0px rgba(0, 0, 0, 0.75);
}
```

or if you need to apply different styles per scrollbar you can do:

```css
.os-scrollbar-horizontal > .os-scrollbar-track {
  box-shadow: 0px -5px 5px 0px rgba(0, 0, 0, 0.75);
}

.os-scrollbar-vertical > .os-scrollbar-track {
  box-shadow: -5px 0px 5px 0px rgba(0, 0, 0, 0.75);
}
```

Here is a small example: https://stackblitz.com/edit/overlayscrollbars-xfyops?file=styles.css
