### ISSUE TITLE
Browser window width jump

### ISSUE THREAD

**Issue by skynet** [KingSora/OverlayScrollbars#121]
If we replace native scrollbar for entire browser window -

How do we fix the problem when page is loading, when native scroll bar is quickly replaced with the Overlay Scrollbar and a jumping is experienced?

**Comment by KingSora** [comment]
Good day!

You could try this CSS rule:

```CSS
html, body {
    overflow: hidden;
}
```
