### ISSUE TITLE
Regression in 1.13.0 - Scrollbar handle does not show

### ISSUE THREAD

**Issue by FSDRE** [KingSora/OverlayScrollbars#256]
**Describe the bug**
This is a regression. Works in 1.12.0, does not work in 1.13.0.

I have a container with the following options:

``` typescript
public scrollerOptions: any = {
    className: 'os-thin',
    paddingAbsolute: true,
    overflowBehavior: {
      x: 'scroll',
      y: 'hidden'
    },
    scrollbars: {
      autoHide: 'move',
      autoHideDelay: 500
    }
  }
```

In 1.12.0 hovering the mouse over the container would show the scroll handle. Does not show up in 1.13.0.

**To Reproduce**
1. Create Container with horizonzally scrollable content
2. Apply above options
3. Hover mouse over container

**Expected behavior**
Scrollbar handle should show on hovering the mouse

**Environment**
 - Used Operating System(s): Win 10 Pro x64
 - Used Browser(s) (with version): Chrome / Firefox latest

**Comment by KingSora** [comment]
Good day!

Are you really sure that `v1.13.0` caused this issue? I tried it here: https://jsfiddle.net/Ldt4pjhw/2/ and everything is working as it should. 

The only thing I can't test there is your `className: 'os-thin'` option, because you're responsible to provide the needed styles for that. Is it possible that you changed the `CSS` file of the previous version and now the update has overwritten those changes?

**Comment by FSDRE** [comment]
Hmmm.... I will investigate more and try to dumb down my case for a StackBlitz.

If I npm install 1.13, it breaks, if I go back to 1.12 it works, so there must be an incompatibility. My code did not change over the last 3 months since I have not even been at work 😄

Conclusion: Your jsfiddle works, my 1.12 works, my 1.13 does not work. We will find out why 😄 

Just for context, here's my os-thin theme working in 1.12 for months now. Have you changed anything in 1.13 regarding CSS styles?

``` scss
.os-thin > .os-scrollbar-horizontal {
  right: 1rem;
  height: 1rem;
  padding: 0rem 0.4rem;
}

.os-thin > .os-scrollbar-vertical {
  bottom: 1rem;
  width: 1rem;
  padding: 0.4rem 0rem;
}

.os-thin.os-host-rtl > .os-scrollbar-horizontal {
  left: 1rem;
  right: 0;
}

.os-thin > .os-scrollbar-corner {
  height: 1rem;
  width: 1rem;
  background-color: transparent;
}

.os-thin > .os-scrollbar > .os-scrollbar-track {
  background: transparent;
}

.os-thin > .os-scrollbar-horizontal > .os-scrollbar-track:before,
.os-thin > .os-scrollbar-vertical > .os-scrollbar-track:before {
  content: '';
  display: block;
  position: absolute;
  background: transparent;
}

.os-thin > .os-scrollbar-horizontal > .os-scrollbar-track:before,
.os-thin > .os-scrollbar-horizontal > .os-scrollbar-track > .os-scrollbar-handle:before {
  left: 0;
  right: 0;
  height: 0.2rem;
  top: 50%;
  margin-top: -0.1rem;
}

.os-thin > .os-scrollbar-vertical > .os-scrollbar-track:before,
.os-thin > .os-scrollbar-vertical > .os-scrollbar-track > .os-scrollbar-handle:before {
  top: 0;
  bottom: 0;
  width: 0.2rem;
  left: 50%;
  margin-left: -0.1rem;
}

.os-thin > .os-scrollbar > .os-scrollbar-track > .os-scrollbar-handle:before {
  content: '';
  display: block;
  position: absolute;
  background: rgba(0, 0, 0, 0.2);
  border-radius: 0.2rem;
}

.os-thin > .os-scrollbar-horizontal > .os-scrollbar-track > .os-scrollbar-handle:hover:before,
.os-thin > .os-scrollbar-horizontal > .os-scrollbar-track > .os-scrollbar-handle.active:before {
  height: 0.4rem;
  margin-top: -0.2rem;
}

.os-thin > .os-scrollbar-vertical > .os-scrollbar-track > .os-scrollbar-handle:hover:before,
.os-thin > .os-scrollbar-vertical > .os-scrollbar-track > .os-scrollbar-handle.active:before {
  width: 0.4rem;
  margin-left: -0.2rem;
}

.os-thin > .os-scrollbar-horizontal > .os-scrollbar-track > .os-scrollbar-handle:hover:before,
.os-thin > .os-scrollbar-vertical > .os-scrollbar-track > .os-scrollbar-handle:hover:before {
  background: rgba(0, 0, 0, 0.4);
}

.os-thin > .os-scrollbar-horizontal > .os-scrollbar-track > .os-scrollbar-handle.active:before,
.os-thin > .os-scrollbar-vertical > .os-scrollbar-track > .os-scrollbar-handle.active:before {
  background: rgba(0, 0, 0, 0.6);
}

.os-thin > .os-scrollbar-horizontal > .os-scrollbar-track > .os-scrollbar-handle {
  height: 100%;
  min-width: 2rem;
}
.os-thin > .os-scrollbar-vertical > .os-scrollbar-track > .os-scrollbar-handle {
  width: 100%;
  min-height: 2rem;
}

.os-thin.os-host-transition > .os-scrollbar-horizontal > .os-scrollbar-track > .os-scrollbar-handle:before {
  transition: height 0.3s, margin-top 0.3s, background 0.2s;
}

.os-thin.os-host-transition > .os-scrollbar-vertical > .os-scrollbar-track > .os-scrollbar-handle:before {
  transition: width 0.3s, margin-left 0.3s, background 0.2s;
}

```

**Comment by FSDRE** [comment]
And sorry for the wrong reproduction example. I have clearly messed something up, because it obviously works. My actual usecase is way more complex and hard to make an easy StackBlitz of. I'll get back to you.

**Comment by KingSora** [comment]
@FSDRE no problem! If you want, you can also upload your project on github inside a private repo or you can also send it to me via email (or something like that).

**Comment by FSDRE** [comment]
@KingSora I got it:

https://stackblitz.com/edit/angular-ivy-leefbt

It has 1.12 installed. Just switch to 1.13 and the scrollbar does not show up anymore.

**Comment by KingSora** [comment]
@FSDRE I figured it out, and it's luckily just a very minor thing.. in order to fix #240 I removed the `z-index` value from the `.os-padding` element. This causes the issue that the scrollbars are now below the content and in your case the background-color is opaque so you won't see the scrollbar anymore. I'll fix this in the next (soon) update but until then you can set the CSS rule:

```css
.os-padding {
  z-index: 0;
}
```

**Comment by FSDRE** [comment]
@KingSora I have `z-index: 1000` on the `.tab` class. If I remove that, it also works, but it is needed since I need to handle other absolutely positioned overlaying elements. Glad it's an easy fix!

**Comment by KingSora** [comment]
Fixed with [version 1.13.1](https://github.com/KingSora/OverlayScrollbars/releases/tag/1.13.1)

**Comment by Baedda** [comment]
Hey @KingSora,
I am sorry to say this, but the new version (1.13.1) is now breaking my implementation. The scrollbar now shows on top of flyouts that can be opened from inside our scroll container.

Since the `.os-padding` container is wrapping the inner scroll content, I find it dangerous to assign a zero z-index to it because this can break a lot. I bet I am not the only one who faces issues with this update.

**Comment by KingSora** [comment]
Good day @Baedda!

Can you show me a example of what you exactly mean? Somehow I need to get the z-index right here...

**Comment by Baedda** [comment]
Hey @KingSora - thanks for the fast answer 👍 
Yes of course - but as you can imagine this is not to easy to explain. I will give it a try tomorrw :)

**Comment by FSDRE** [comment]
@Baedda You are the master of your app. You can run in all sorts of z-index discrepancies if you're running multiple JS frameworks at the same time for example or if two different libraries run different "z-index patterns". It is not necessarily the framework or the library that needs to fix those issues.

I use the Angular Material Dialog and I have also had some "background elements" overlapping the popup. The fix was easy setting
```css
.cdk-overlay-container {
  z-index: 4000 !important;
}
```
What I want to say is: if your fly-in gets shoved behind the scrollbar, why don't you just set the z-index of your fly-in to an appropriate value so it is the top-most again? I think @KingSora can't provide a generic solution to all z-index issues with his library 😄
