### ISSUE TITLE
Issue with Overlays on an  ul.dropdown-menu element

### ISSUE THREAD

**Issue by realleoman** [KingSora/OverlayScrollbars#31]
Hi there:

I found a new issue when using the OverlayScrollbars on a Materialize dropdown-menu element.

I have this part of the code on my Initialization method (I use jquery)

```javascript
$(document).ready(function(){
    $('.dropdown-menu').overlayScrollbars({ 
       className: "os-theme-dark",
        scrollbars : {
        visibility  : "auto",
        autoHide  : "move",
        touchSupport  : true
      },
    }); 
```

Then I construct my dropdown-menu dynamically and here are some CSS snippets from the materialize.css file

```scss
.open>.dropdown-menu {
	display: block;
}
.open>a {
	outline: 0;
}

.dropdown-menu {
	position: absolute;
	top: 100%;
	left: 0;
	z-index: 1000;
	display: none;
	float: left;
	min-width: 160px;
	padding: 30px 0;
	margin: 2px 0 0;
	text-align: left;
	list-style: none;
	background-color: #fff;
	-webkit-background-clip: padding-box;
	background-clip: padding-box;
	border: 1px solid #ccc;
	border: 1px solid rgba(0,0,0,.15);
	border-radius: 4px;
	-webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
	box-shadow: 0 6px 12px rgba(0,0,0,.175);

	li > a {
		display: block;
		padding: 5px 40px;
		clear: both;
		font-weight: 400;
		line-height: 1.42857143;
		color: #333;
		white-space: nowrap;

		&:hover {
			background-color: #0064b3;
			color: #fff;
			text-decoration: none;
		}
	}
}

.dropdown .dropdown-menu li > a {
  &:hover {
    color: #FFBA20;
  }
}
```

So here it is how my dropdown menu element looks like without OverlaysScrollbar on Mac OS X
<img width="245" alt="no overlays enabled mac os x" src="https://user-images.githubusercontent.com/699501/39594434-4d45e266-4ed2-11e8-80d2-d18ebfafcdfd.png">

So here it is how my dropdown menu element looks like without OverlaysScrollbar on Windows (look at the scrolling bar)
<img width="254" alt="no overlays enabled windows" src="https://user-images.githubusercontent.com/699501/39594442-5159944c-4ed2-11e8-9802-85e14bf233ce.png">

And this is how my dropdown menu element looks like when using OverlaysScrollbar. It gets all messed up.
<img width="259" alt="with overlays enabled" src="https://user-images.githubusercontent.com/699501/39594452-5481feb6-4ed2-11e8-9a73-cda8a7e0f4b0.png">

@KingSora, my question is:  How can I fix this behavior to respect the CSS styling on my materialize CSS class?
