### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by glassesUSA** [KingSora/OverlayScrollbars#369]
Hi, 

I am trying to add `scroll-behavior: smooth` to the element so when an inner target is clicked it will scroll smoothly down but it doesnt appear to be working. Which element does the style need to be applied to?

**Comment by KingSora** [comment]
Good day @glassesUSA 

The `viewport` element is doing the scrolling, so the selector should be something like this:
```css
.os-viewport {
  scroll-behavior: smooth;
}
```
