### ISSUE TITLE
use css scrollbars for theming

### ISSUE THREAD

**Issue by renatodeleao** [KingSora/OverlayScrollbars#478]
**problem**
Overriding styles requires manual investigation of how your CSS specificity is done for the several interactive scenarios. So the current was is inspect source, copying the selector and doing the override.

https://github.com/KingSora/OverlayScrollbars/blob/309ddd7a90685948a5b21658f0a40ea9869b5516/packages/overlayscrollbars/src/styles/scrollbars.scss#L139-L141

**solution**
Using CSS variables you could hide the CSS implementation details from consumers and just let them know what variables are available to tweak the same way you do with javascript config options. Peaking on the previous example:

```diff
+  .os-theme-dark {
+    --os-scrollbar-track-bg-hover: rgba(0, 0, 0, 0.55);
+ }

 .os-theme-dark.os-scrollbar:hover > .os-scrollbar-track > .os-scrollbar-handle { 
-   background: rgba(0, 0, 0, 0.55); 
-   background: var(--os-scrollbar-track-bg-hover);
 } 
```

On my app I just need to override this variable the same way I do with plugin javascript options

```scss
// my component/app
.os-theme-dark {
    --os-scrollbar-track-bg-hover: lime;
} 
```

Let me know if this is something you're interested in and thanks for the work on the plugin! ✌️

**Comment by KingSora** [comment]
Good day @renatodeleao 

I've considered this and I'm already working with custom css properties in the code ([here](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars/src/styles/structure.scss#L137-L138) and [here](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars/src/plugins/scrollbarsHidingPlugin/scrollbarsHidingPlugin.ts#L170-L173)) and the `env()` function is also [detecting the browser support](https://github.com/KingSora/OverlayScrollbars/blob/master/packages/overlayscrollbars/src/environment.ts#L54-L55). 

That beeing said, as I'm still supporting `IE11` which isn't supporting css custom properties the default would be to keep the scrollbar styles without css custom props. However I would be open for providing a second `css` file which support css custom props for the scrollbar styles and the consumer can then choose what to use.

**Comment by renatodeleao** [comment]
Good day! Good to know that it is on the radar!

> That being said, as I'm still supporting IE11 which isn't supporting css custom properties

Uhhh unusual these days 😛 If I remember that correctly, declaring the hardcoded `prop: value` pair as a fallback before the one with the `var` would still work in IE because it would ignore the latter as an "invalid property declaration" while supporting browsers would just is as normal.

```scss
.test {
   --bg: red;
   
    background-color: red; // for IE
    background-color: var(--bg) // IE will ignore it, and since everyone else supports this will be applied instead
}
```

There's a couple of `postCSS` plugins that handle it [here](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-custom-properties) and [here](https://github.com/MadLittleMods/postcss-css-variables#preserve-default-false) but providing a second file is also an option, but a bit more work to maintain I guess.

Anyways thanks for the quick reply! Let me know If I can help with something!

**Comment by KingSora** [comment]
@renatodeleao that looks like a nice proposal. I'll see what I can do :)

**Comment by KingSora** [comment]
@renatodeleao I've published version [2.1.0](https://www.npmjs.com/package/overlayscrollbars/v/2.1.0) where I implemented a set of Custom CSS Properties:

```scss
.os-scrollbar {
  // The size of the scrollbar
  --os-size: 0;
  // The axis-perpedicular padding of the scrollbar (horizontal: padding-y, vertical: padding-x)
  --os-padding-perpendicular: 0;
  // The axis padding of the scrollbar (horizontal: padding-x, vertical: padding-y)
  --os-padding-axis: 0;
  // The border radius of the scrollbar track
  --os-track-border-radius: 0;
  // The background of the scrollbar track
  --os-track-bg: none;
  // The :hover background of the scrollbar track
  --os-track-bg-hover: none;
  // The :active background of the scrollbar track
  --os-track-bg-active: none;
  // The border of the scrollbar track
  --os-track-border: none;
  // The :hover background of the scrollbar track
  --os-track-border-hover: none;
  // The :active background of the scrollbar track
  --os-track-border-active: none;
  // The border radius of the scrollbar handle
  --os-handle-border-radius: 0;
  // The background of the scrollbar handle
  --os-handle-bg: none;
  // The :hover background of the scrollbar handle
  --os-handle-bg-hover: none;
  // The :active background of the scrollbar handle
  --os-handle-bg-active: none;
  // The border of the scrollbar handle
  --os-handle-border: none;
  // The :hover border of the scrollbar handle
  --os-handle-border-hover: none;
  // The :active border of the scrollbar handle
  --os-handle-border-active: none;
  // The min size of the scrollbar handle
  --os-handle-min-size: 33px;
  // The max size of the scrollbar handle
  --os-handle-max-size: none;
  // The axis-perpedicular size of the scrollbar handle (horizontal: height, vertical: width)
  --os-handle-perpendicular-size: 100%;
  // The :hover axis-perpedicular size of the scrollbar handle (horizontal: height, vertical: width)
  --os-handle-perpendicular-size-hover: 100%;
  // The :active axis-perpedicular size of the scrollbar handle (horizontal: height, vertical: width)
  --os-handle-perpendicular-size-active: 100%;
  // Increases the interactive area of the scrollbar handle.
  --os-handle-interactive-area-offset: 0;
}
```
Those can be set for both scrollbars at the same time or per scrollbar axis.

You can now also find a [`Styling section`](https://github.com/KingSora/OverlayScrollbars#styling) in the README which documents all css variables, class names and html markup of the scrollbars.

**Comment by sebastienbarre** [comment]
This sounds great but the "Styling in depth" documentation is not very clear as to where or how to use these properties. In a CSS file? Before including `overlayscrollbars/overlayscrollbars.css`? After? 
Thanks

**Comment by KingSora** [comment]
@sebastienbarre it doesn't really mater whether you use the custom css properties before or after including the css file (as long as you include it). If you are using other css properties in conjunction with the custom css properties I would place the styles after the css file because otherwise they might not overwrite defaults.

The workflow is like this:
1. Think about your theme and how it should look
2. Create a class selector with the name of your theme like described in "styling in depth". Here I'm using `os-theme-custom`:
```scss
// horizontal and vertical scrollbar are 10px 
.os-theme-custom {
  --os-size: 10px;
}

// horizontal scrollbar is 10px
.os-theme-custom.os-scrollbar-horizontal {
  --os-size: 10px;
}
// vertical scrollbar is 20px
.os-theme-custom.os-scrollbar-vertical {
  --os-size: 20px;
}
```
3. Use the theme by initializing `OverlayScrollbars` with you chosen class name:
```js
OverlayScrollbars(document.body, {
  scrollbars: {
    theme: 'os-theme-custom'
  }
});
```
