### ISSUE TITLE
Has `os-scrollbar-corner` been depreciated?

### ISSUE THREAD

**Issue by pvlvstepan** [KingSora/OverlayScrollbars#518]
**Describe the bug**
[This comment](https://github.com/KingSora/OverlayScrollbars/issues/5#issuecomment-354257055) mentions that there is an element called `os-scrollbar-corner` that serves a purpose of connecting two scrollbars together and it can be enabled via `resize` option. During investigation I have found that none of the documentation actually mentions this option, and the element is not being rendered in the DOM at all. This leaves a weird visual behaviour of an empty corner at the point where two scrollbars connect when scrollbar track is not transparent. 

**Expected behavior**
I was expecting to see two scrollbars connect in the corner with a matching background colour.

**Examples**
You can see the issue in [this example](https://codesandbox.io/s/romantic-dhawan-0rlkq1)

**Environment**

- The issue seems to be present across different browsers
- `overlayscrollbars`: 2.1.1
- `overlayscrollbars-react`: 0.5.0

**Comment by KingSora** [comment]
Good day @pvlvstepan 

Indeed, im `v2` the corner element has been removed in an attempt to make the library smaller in size and to reduce the api surface. I considered this as a minor feature which wasnt used very often since most of the time only one axis is scrollable. 

It was also removed because in `v2` you can clone and position scrollbars independently wherever you want, which would've made the implementation event more complex.

That being said, it could be brought back in the form of a plugin.

**Comment by pvlvstepan** [comment]
Hi, @KingSora

Thanks for in depth answer and explanation on the issue. As of now I'm trying to come up with a workaround to create and attach a custom corner element on `initialized` event. Is it possible to listen to scrollbars visibility state? And how can I determine if both scrollbars are enabled? This is to make sure that corner element is not attached when only horizontal or only vertical scrollbar is enabled.

**Comment by pvlvstepan** [comment]
I couldn't find a way to add `os-scrollbar-visible` and `os-scrollbar-auto-hidden` to the corner element via events, however I managed to create a working workaround using css only. Not the best solution but works fine. 

```typescript
<OverlayScrollbarsComponent
    options={{
        scrollbars: {
            theme: 'overlay-scrollbar-table',
            autoHide: 'move',
        },
    }}
    events={{
        initialized: (i) => {
            // Get elements and options of the OverlayScrollbarsComponent
            const elements = i.elements();
            const options = i.options();
            // Create corner element and add the theme className to it
            const corner = document.createElement('div');
            corner.className = classNames(
                options.scrollbars.theme,
                'os-scrollbar-corner',
            );
            // Attach corner element to the target element
            elements.target.appendChild(corner);
        },
    }}
    defer
>
...
</OverlayScrollbarsComponent>
```

And then in styles where I created the scrollbar theme I added the following:

```scss
.overlay-scrollbar-table {
    ...
    &.os-scrollbar-corner {
        position: absolute;
        bottom: 0;
        right: 0;
        width: var(--os-size);
        height: var(--os-size);
        background: var(--os-track-bg);
        border-top: var(--os-track-border);
        border-left: var(--os-track-border);
        transition: opacity 0.15s, visibility 0.15s;
    }
    &.os-scrollbar-visible,
    &.os-scrollbar-interaction.os-scrollbar-visible {
        & ~ .os-scrollbar-corner {
            opacity: 1;
            visibility: visible;
        }
    }
    &.os-scrollbar-auto-hidden {
        & ~ .os-scrollbar-corner {
            opacity: 0;
            visibility: hidden;
        }
    }
    &.os-scrollbar-cornerless {
        & ~ .os-scrollbar-corner {
            display: none;
        }
    }
}
```

**Comment by KingSora** [comment]
@pvlvstepan Currently there is no way to listen to visibility changes of the scrollbars. Your solution looks pretty good though, are there cases where this solution wasn't working as expected?

**Comment by pvlvstepan** [comment]
hey, @KingSora
I haven't had any issues with this solution so far and everything is working as expected. A plugin for this would be useful thought.
I guess we can mark this issue as resolved (with a workaround) and you may close it or do whatever is appropriate. Thanks!

**Comment by KingSora** [comment]
@pvlvstepan I've created an plugin which helps with this issue:

```ts
const osScrollbarCornerPlugin = {
  'scrollbarCornerPlugin': {
    instance: (instance, event) => {
      const { 
        scrollbarVertical,
      } = instance.elements();

      const cornerClassName = 'os-scrollbar-corner';
      const corner = document.createElement('div');

      event('initialized', () => {
        scrollbarVertical.scrollbar.parentElement?.append(corner);
      });

      event('updated', () => {
        const { scrollbars: { theme } } = instance.options();
        corner.className = `${cornerClassName} ${theme}`;
      })

      event('destroyed', () => corner.remove());
    },
  }
} satisfies InstancePlugin;
```

The corresponding CSS:
```css
.os-scrollbar {
  background: var(--os-scrollbar-bg);
}
.os-scrollbar-corner {
  position: absolute;
  bottom: 0;
  right: 0;
  width: var(--os-size);
  height: var(--os-size);
  background: var(--os-scrollbar-bg);
  transition: opacity 0.15s, visibility 0.15s;
}
.os-scrollbar-visible,
.os-scrollbar-interaction.os-scrollbar-visible ~ .os-scrollbar-corner {
  opacity: 1;
  visibility: visible;
}
.os-scrollbar-auto-hide-hidden ~ .os-scrollbar-corner {
  opacity: 0;
  visibility: hidden;
}
.os-scrollbar-cornerless ~ .os-scrollbar-corner {
  display: none;
}
.os-scrollbar.os-scrollbar-rtl ~ .os-scrollbar-corner {
  left: 0;
  right: auto;
}
```

It can be added like:
```ts
OverlayScrollbars.plugin(osScrollbarCornerPlugin)
```

The CSS adds a new styling custom css property called `--os-scrollbar-bg`, which applies to the scrollbar and corner element and can be assigned like:

```css
.os-scrollbar,
.os-scrollbar-corner {
  --os-scrollbar-bg: coral;
}
```

Here is a small example: https://stackblitz.com/edit/overlayscrollbars-react-4g9xqd?file=src%2Fmain.tsx
