### ISSUE TITLE
scollbar not updated while using height transition

### ISSUE THREAD

**Issue by ducheng1** [KingSora/OverlayScrollbars#585]
When I use transition for a container to animate its change on height, the scrollbar just not updated and can't scroll anyway, until another container appears and change the parent element's height.

## how this problem occured
![image](https://github.com/KingSora/OverlayScrollbars/assets/51262427/edf9116b-7ba7-4a38-a737-989d582da4e8)

## codes
``` html
  <div
    class="regular-layout flex flex-col relative"
    :style="maxHeight && collapsed ? { height: maxHeight } : {}"
  />
```
``` css
.regular-layout {
  max-width: calc(100% - 32px);
  margin: 16px;
  color: var(--trim-text-color);
  transition: height 0.25s;
  overflow: hidden;
}

.opened {
  height: v-bind(elHeight);
}
```
