### ISSUE TITLE
How to use snap scroll with overlay scrollbar?

### ISSUE THREAD

**Issue by hsharma89** [KingSora/OverlayScrollbars#96]
I have to use snap scroll with overlay scrollbar. i tried using  the following css but its not working.

 scroll-snap-type: y mandatory;
    scroll-snap-type: mandatory;
    -ms-scroll-snap-type: mandatory;
	-moz-scroll-snap-type: mandatory;
    -webkit-scroll-snap-type: mandatory;
    -webkit-scroll-snap-destination: 0% 0%;
	-webkit-overflow-scrolling: touch;

Thanks
Himanshu Sharma

**Comment by KingSora** [comment]
Good day!

Basically this is already correct, you just need to use the correct selector:

```css
#your-element.os-host > .os-padding > .os-viewport {
    scroll-snap-type: y mandatory;
    scroll-snap-type: mandatory;
    -ms-scroll-snap-type: mandatory;
    -moz-scroll-snap-type: mandatory;
    -webkit-scroll-snap-type: mandatory;
    -webkit-scroll-snap-destination: 0% 0%;
    -webkit-overflow-scrolling: touch;
}
```
