### ISSUE TITLE
scroll-behavior property has no effect

### ISSUE THREAD

**Issue by b3u** [KingSora/OverlayScrollbars#97]
Without changing the scrollbar, the addition of the scroll-behavior property makes the page scroll smoothly (smooth-scroll). With the addition of this plugin, the property has no effect.
```css
html{scroll-behavior: smooth}
```

**Comment by KingSora** [comment]
Good day!

Thats because the plugin is wrapping the content. The `viewport` element is responsible for the actual scrolling, so applying this style to this element should solve your issue.

```CSS
html,
body.os-host > .os-padding > .os-viewport {
    scroll-behavior: smooth
}
```
